- name: "Restart {{ APP_NAME }}"
  listen: Restart app 
  become: yes
  service:
    name: "{{ APP_NAME }}"
    state: restarted
    daemon-reload: yes
  when: not ansible_check_mode

# vim: ai et ts=4 sts=4 sw=4 nu
