---
- name: Create app logging directories
  become: yes
  file:
    path: "/var/log/{{ app_name }}"
    owner: ubuntu
    group: ubuntu
    mode: 0775
    state: directory

- name: Enable logrotate for "{{ app_name }}"
  become: yes
  template:
    src: templates/logrotate.j2
    dest: "/etc/logrotate.d/{{ app_name}}"

- name: Install python script app file
  template:
    src: "{{ APP_SCRIPT }}.j2"
    dest: "/opt/apps/{{ app_name }}/{{ APP_SCRIPT }}"
  notify:
    - Restart twitter app

- name: Install environment variables
  template:
    src: env.j2
    dest: "/opt/apps/{{ app_name }}/.env"
    owner: ubuntu
    group: ubuntu
    mode: 0600
  notify:
    - Restart twitter app

- name: Enable logrotate for "{{ app_name }}"
  become: yes
  template:
    src: templates/logrotate.j2
    dest: "/etc/logrotate.d/{{ app_name}}"

- name: Install hello_world app file
  template:
    src: "{{ HELLO_WORLD_APP_SCRIPT }}.j2"
    dest: "/opt/apps/{{ app_name }}/{{ HELLO_WORLD_APP_SCRIPT }}"
  notify:
    - Restart twitter app

- name: Install environment variables
  template:
    src: env.j2
    dest: "/opt/apps/{{ app_name }}/.env"
  notify:
  notify:
    - Restart twitter app

- name: Create systemd app service file
  become: yes
  template:
    src: templates/twitter_app_service.j2
    dest: "/usr/lib/systemd/system/{{ app_name }}.service"
  notify:
    - Restart twitter app

- name: App enable & start
  become: yes
  service:
    name: "{{ app_name }}"
    enabled: yes
    state: started

- name: Rsync twitter helper scripts
  synchronize:
    src: files/twitter_helper_scripts
    dest: "/opt/apps/{{ app_name }}"
    archive: yes
    recursive: yes

- name: Install production app
  synchronize:
    src: "files/{{ item }}"
    dest: "/opt/apps/{{ app_name }}/{{ item }}"
  with_items: "{{ Production scripts }}"

# vim: ai et ts=2 sw=2 sts=2 nu
