---
- name: Create app logging directories
  become: yes
  file:
    state: directory
    path: "/var/log/{{ APP_NAME }}"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: 0775

- name: Enable logrotate for "{{ APP_NAME }}"
  become: yes
  template:
    src: templates/logrotate.j2
    dest: "/etc/logrotate.d/{{ APP_NAME}}"

- name: Install environment variables
  template:
    src: env.j2
    dest: "{{ PATH_TO_RETWEET_APP }}/.env"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: 0644
  notify:
    - Restart app

- name: Install app script 
  copy:
    src: "{{ APP_SCRIPT }}"
    dest: "{{ PATH_TO_RETWEET_APP}}/{{ APP_SCRIPT }}"
  notify:
    - Restart app

- name: Create systemd app service file
  become: yes
  template:
    src: templates/app_service.j2
    dest: "/usr/lib/systemd/system/{{ APP_NAME }}.service"
  notify:
    - Restart app

- name: "Check if systemd file exists"
  become: yes
  stat:
    path: "/usr/lib/systemd/system/{{ APP_NAME }}.service"
  register: systemd_file

- name: App enable & start
  become: yes
  service:
    name: "{{ APP_NAME }}"
    enabled: yes
    state: started
  when: systemd_file.stat.exists

# vim: ai et ts=2 sw=2 sts=2 nu
