---
- name: Check hostame variable
  debug:
    msg: "HOSTNAME: {{ HOSTNAME }}"

- name: setup vimrc
  copy:
    src: vimrc
    dest: "{{ HOME }}/.vimrc"

- name: change hostname
  become: yes
  template:
    src: hostname.j2
    dest: /etc/hostname

- name: add hostname to /etc/hosts
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ FQDN }} {{ HOSTNAME }}"
    create: yes

- name: release cloud cfg from managing /etc/hosts
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
    regexp: "^manage_etc_hosts:"
    line: "manage_etc_hosts: false"

- name: set timezone correctly
  become: yes
  file:
    src: "/usr/share/zoneinfo/{{ LOCAL_TIMEZONE }}"
    path: /etc/localtime
    state: link

# vim: ai et ts=2 sw=2 sts=2 nu

