---
- name: Create app directory
  file:
    state: directory
    path: "/opt/apps/{{ app_name }}"
    owner: ubuntu
    group: ubuntu
    mode: '0775'

- name: Install requirements file
  template:
    src: requirements.j2
    dest: "/opt/apps/{{ app_name }}/requirements.txt"
    owner: ubuntu
    group: ubuntu


- name: Install specified python requirements
  pip:
    requirements: "/opt/apps/{{ app_name }}/requirements.txt"
    virtualenv: "/opt/apps/{{ app_name }}/venv"
    virtualenv_command: /usr/bin/virtualenv # python 3

# vim: ai et ts=2 sts=2 sw=2 nu
