---
- name: Create app directory
  become: yes
  file:
    state: directory
    path: "{{ PATH_TO_RETWEET_APP }}"
    mode: 0775
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: "Check if {{ PATH_TO_RETWEET_APP }} exists"
  become: yes
  stat:
    path: "{{ PATH_TO_RETWEET_APP }}"
  register: app_dir

- name: Install requirements file
  copy:
    src: requirements.txt
    dest: "{{ PATH_TO_RETWEET_APP }}/requirements.txt"
    owner: "{{ USER }}"
    group: "{{ USER }}"
  when: app_dir.stat.exists

- name: Install specified python requirements
  pip:
    requirements: "{{ PATH_TO_RETWEET_APP }}/requirements.txt"
    virtualenv: "{{ PATH_TO_RETWEET_APP }}/venv"
    virtualenv_command: /usr/bin/virtualenv
  when: app_dir.stat.exists and not ansible_check_mode

# vim: ai et ts=2 sts=2 sw=2 nu
