---
- hosts: current_hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
    HOME: "{{ lookup('env', 'HOME') }}"
  vars_files:
    - /opt/apps/configuration/private_vars.yaml
  connection: local
  roles:
    - role: prep_work
      tags: [prep_work]
    - role: virtualenv
      tags: [virtualenv]
    - role: install_app
      tags: [install_app]

# vim: ai et ts=2 sw=2 sts=2 nu
