---
HOSTNAME: 'your-hosthame'
FQDN: 'your-hostname.yourdomain.com'
LOCAL_TIMEZONE: 'America/New_York'

PATH_TO_RETWEET_APP: '/path/to/retweet_app'
APP_NAME: 'retweet_app'

# Use for first install
APP_SCRIPT: 'hello.py' 
# Use for production
# streaming_app.py

# Intended for .env file
LOG_TO_FILE: 'yes' 
LOGGING_FILE_NAME: '/var/log/retweet_app/retweet.log'
LOGLEVEL: 'info'




#app_name: 'your_app_name' # used to make app directory
#HELLO_WORLD_APP_SCRIPT: hello_world.py
#PATH_TO_PYTHON: '/path/to/virtualenv/python, e.g. /opt/apps/my_app/venv/bin/python'
#
#LOG_LEVEL: WARNING
#
#Production_scripts:
#  - config.py
#  - streaming_app.py
#  - get_user_screen_name.py
#
## Toggle this for testing with hello_world
#LIVE_APP_SCRIPT: streaming_app.py
##LIVE_APP_SCRIPT: hello_world.py
#
#HELLO_WORLD: 'Hello World: used for testing journald ...'
#HELLO_WORLD_ERROR: 'Blue Moon: used for testing journald ...'
#API_KEY: 'api_key'
#API_KEY_SECRET: 'api_key_secret'
#ACCESS_TOKEN: 'access_token'
#ACCESS_TOKEN_SECRET: 'access_token_secret'
#BEARER_TOKEN: 'bearer_token'
#
#### All of these will have their Tweets retweeted ("published" by this app)
#IDS_TO_FOLLOW: 'user.id_#1,user.id_#2,user.id #3, user.id_#4' # all ids go here
#
#### These will not have their Quotes nor their Retweets retweeted, only their Tweets ("published" by this app)
#IDS_TO_PUBLISH_ONLY_TWEETS: 'user.id_#1,user.id_#2'
#
#### These will have their Tweets and Quotes retweeted, but not their Retweets ("published" by this app)
#IDS_TO_PUBLISH_TWEETS_AND_QUOTES: 'user.id_#3'
#
#### Those "IDS_TO_FOLLOW" not mentioned in the above two variables will
#### have their Tweets, their Quotes, and their Retweets retweeted ("published" by this app)
#### In this case it would be user.id_#4
#
#INCLUDE_REPLYS_AND_SELF_RETWEETS_IN_LOG: "no" # string: "yes" or "no"
#
#Publish_Live: 'no'
#
## vim: ai et ts=2 sw=2 sts=2 nu
