---
HOSTNAME: 'your.hostname.org'
local_timezone: 'America/New_York'
app_name: 'your_app_name' # used to make app directory
tweepy_version: '4.5.0'
HELLO_WORLD_APP_SCRIPT: hello_world.py
PATH_TO_PYTHON: '/path/to/virtualenv/python, e.g. /opt/apps/my_app/venv/bin/python'

Production_scripts:
  - config.py
  - logger.py
  - streaming_app.py
  - get_user_screen_name.py

# Toggle this for testing with hello_world
LIVE_APP_SCRIPT: streaming_app.py
#LIVE_APP_SCRIPT: hello_world.py

HELLO_WORLD: 'Hello World: used for testing journald ...'
HELLO_WORLD_ERROR: 'Blue Moon: used for testing journald ...'
API_KEY: 'api_key'
API_KEY_SECRET: 'api_key_secret'
ACCESS_TOKEN: 'access_token'
ACCESS_TOKEN_SECRET: 'access_token_secret'
BEARER_TOKEN: 'bearer_token'

IDS_TO_FOLLOW: 'user.id #1,user.id #2,user.id #3, user.id #4' # all ids go here
IDS_TO_PUBLISH_ONLY_TWEETS: 'user.id #1,user.id #2' # no Quotes, no Retweets
IDS_TO_PUBLISH_TWEETS_AND_QUOTES: 'user.id #3' # No Retweets

INCLUDE_REPLYS_AND_SELF_RETWEETS_IN_LOG: "no" # string: "yes" or "no"

# vim: ai et ts=2 sw=2 sts=2 nu
